# Generated by Django 4.1.3 on 2022-11-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_img', models.FileField(upload_to='cosmic/coupons/')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Coupon creation date')),
                ('modifed_date', models.DateField(auto_now=True, verbose_name='Coupon modified date')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmic.phone')),
            ],
        ),
    ]
