# Generated by Django 4.1.3 on 2022-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='modifed_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
