# Generated by Django 4.1.3 on 2022-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0002_alter_phone_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='cardnumber',
            field=models.IntegerField(null=True),
        ),
    ]
