# Generated by Django 4.1.3 on 2022-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0003_alter_phone_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cupon_img',
            field=models.ImageField(upload_to='cosmic/coupons/'),
        ),
    ]
